version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 1
    # volumes:
    #   - ./db_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

# volumes:
#   db_data:
#   wordpress:
